// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcTkMk5ELA0nWPB6o_x3KJUQVdmhZIScA',
    appId: '1:858143106580:web:c6840a065dad3300abe901',
    messagingSenderId: '858143106580',
    projectId: 'sayyarati',
    authDomain: 'sayyarati.firebaseapp.com',
    storageBucket: 'sayyarati.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtQq47Vt3YY41d5QObfbi__LOSnABEmE',
    appId: '1:858143106580:android:a0683957187a1053abe901',
    messagingSenderId: '858143106580',
    projectId: 'sayyarati',
    storageBucket: 'sayyarati.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7AEg1fyoucumGgMF1iDDYO5WNwAcOgcs',
    appId: '1:858143106580:ios:34a87ac2514e20aeabe901',
    messagingSenderId: '858143106580',
    projectId: 'sayyarati',
    storageBucket: 'sayyarati.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );
}
